version: "3"

volumes:
  mysql-data:

services:
  mysql:
    image: mysql:5.7 # You can use latest version, but in that case you need to change the identification to "mysql_native_password".
    ports:
        - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - ./src/infrastructure/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
